# Generated by Django 4.2.9 on 2025-06-21 10:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Strategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strategy_name', models.CharField(max_length=255)),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('activity_title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('funding_agency', models.CharField(blank=True, max_length=200)),
                ('implementing_agency', models.CharField(blank=True, max_length=200)),
                ('collaborating_agency', models.CharField(blank=True, max_length=200)),
                ('sponsored_by', models.CharField(blank=True, max_length=200)),
                ('facilitated_by', models.CharField(blank=True, max_length=200)),
                ('participants', models.TextField(blank=True, help_text='List of participants, comma-separated or similar.')),
                ('proof_image', models.ImageField(blank=True, null=True, upload_to='proofs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
